@startuml

interface IObserver {
    void response(String data)
}
class Observer1 implements IObserver {
    + void response(String data)
}
class Observer2 implements IObserver {
    + void response(String data)
}
class Observable {
    # List<IObserver> observers
    + void add(IObserver observer)
    + void remove(IObserver observer)
    + void notifyObserver()
}
Observable *- IObserver

@enduml